I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 79, in script call
    call chapter1
  File "game/Chapter8.rpy", line 167, in script
    with mouveoutleft
  File "game/Chapter8.rpy", line 167, in <module>
    with mouveoutleft
NameError: name 'mouveoutleft' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 79, in script call
    call chapter1
  File "game/Chapter8.rpy", line 167, in script
    with mouveoutleft
  File "C:\Users\LiveseyJackson\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 1436, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\LiveseyJackson\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\LiveseyJackson\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Chapter8.rpy", line 167, in <module>
    with mouveoutleft
NameError: name 'mouveoutleft' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
The Hollows 1.0
Fri Feb 11 17:31:28 2022
